name: Deploy FetchSocialData Lambda

on:
  push:
    paths:
      - 'lambdas/fetchSocialData/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies and package Lambda
        run: |
          mkdir -p build
          cp lambdas/fetchSocialData/lambda_function.py build/
          pip install requests feedparser -t build/
          cd build
          zip -r ../function.zip .

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name FetchSocialData \
            --zip-file fileb://function.zip
